Refactoring workflow (#448)

diff --git a/.github/workflows/stable-build.yml b/.github/workflows/stable-build.yml
--- a/.github/workflows/stable-build.yml
+++ b/.github/workflows/stable-build.yml
@@ -14,10 +14,12 @@ jobs:
   build:
     name: Build 
     runs-on: ubuntu-latest
+    continue-on-error: ${{ matrix.condition }}
     strategy:
       matrix:
         images: ["documentserver-stable"]
         edition: ["", "-ee", "-de"]
+        condition: [true]
     steps:
       - name: Checkout code 
         uses: actions/checkout@v3
@@ -39,7 +41,7 @@ jobs:
         run: |
           echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
 
-      - name: Build documentserver-stable
+      - name: Build documentserver-release
         run: |
           TAG=$(echo ${{ steps.tag_name.outputs.SOURCE_TAG }} | sed 's/^.//; s/-stable//')
           SHORTER_TAG=$(echo ${TAG} | grep -o -P '^[\d]+\.[\d]+\.[\d]+')
@@ -55,9 +57,11 @@ jobs:
                    SHORTEST_TAG=$SHORTEST_TAG \
                    docker buildx bake \
                    -f docker-bake.hcl ${{ matrix.images }} \
-                   --push ;
-             else
-                echo "FAILED: Image with tag $TAG do not presented on docker.hub >> build will not started >> exit with 0"
+                   --push 
+                echo "DONE: Build success >> exit with 0"
                 exit 0
+             else
+                echo "FAILED: Image with tag $TAG do not presented on docker.hub >> build will not started >> exit with 1"
+                exit 1
              fi
         shell: bash
